/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Questions;
import java.text.NumberFormat;

/**
 *
 * @author Calvin
 */
public class TipCalculator extends javax.swing.JFrame {

    /**
     * Creates new form TipCalculator
     */
    public TipCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billDisplayLabel = new javax.swing.JLabel();
        billTextField = new javax.swing.JTextField();
        tip10PercentButton = new javax.swing.JButton();
        tip15PercentButton = new javax.swing.JButton();
        tip20PercentButton = new javax.swing.JButton();
        tipDisplayLabel = new javax.swing.JLabel();
        actualTip = new javax.swing.JLabel();
        tipAmountDisplayLabel = new javax.swing.JLabel();
        titleBill = new java.awt.Label();
        amountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        billDisplayLabel.setText("Total Bill:");

        tip10PercentButton.setText("10% Tip");
        tip10PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip10PercentButtonActionPerformed(evt);
            }
        });

        tip15PercentButton.setText("15% Tip");
        tip15PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip15PercentButtonActionPerformed(evt);
            }
        });

        tip20PercentButton.setText("20% Tip");
        tip20PercentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tip20PercentButtonActionPerformed(evt);
            }
        });

        tipDisplayLabel.setText("Actual Tip:");

        tipAmountDisplayLabel.setText("        ");

        titleBill.setText("Tip Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualTip)
                    .addComponent(tip10PercentButton)
                    .addComponent(tip15PercentButton)
                    .addComponent(tip20PercentButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tipDisplayLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tipAmountDisplayLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(billDisplayLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(billTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(titleBill, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billDisplayLabel)
                    .addComponent(billTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip10PercentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip15PercentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip20PercentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipDisplayLabel)
                    .addComponent(tipAmountDisplayLabel)
                    .addComponent(amountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actualTip)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tip10PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip10PercentButtonActionPerformed
        // TODO add your handling code here:
        double totalBill = Double.parseDouble(billTextField.getText());
        String tip10Percent = NumberFormat.getCurrencyInstance().format(totalBill * .1);
        tipAmountDisplayLabel.setText(tip10Percent);
    }//GEN-LAST:event_tip10PercentButtonActionPerformed

    private void tip15PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip15PercentButtonActionPerformed
        // TODO add your handling code here:
       double totalBill = Double.parseDouble(billTextField.getText());
       String tip15Percent = NumberFormat.getCurrencyInstance().format(totalBill * .15);
       tipAmountDisplayLabel.setText(tip15Percent);
    }//GEN-LAST:event_tip15PercentButtonActionPerformed

    private void tip20PercentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tip20PercentButtonActionPerformed
        // TODO add your handling code here:
        double totalBill = Double.parseDouble(billTextField.getText());
        String tip20Percent = NumberFormat.getCurrencyInstance().format(totalBill * .2);
        tipAmountDisplayLabel.setText(tip20Percent);
    }//GEN-LAST:event_tip20PercentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualTip;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel billDisplayLabel;
    private javax.swing.JTextField billTextField;
    public javax.swing.JButton tip10PercentButton;
    public javax.swing.JButton tip15PercentButton;
    private javax.swing.JButton tip20PercentButton;
    public javax.swing.JLabel tipAmountDisplayLabel;
    private javax.swing.JLabel tipDisplayLabel;
    private java.awt.Label titleBill;
    // End of variables declaration//GEN-END:variables
}
